/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameInterface;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form userInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameTextArea = new javax.swing.JTextArea();
        gameTextField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        currentRoomTitleLabel = new javax.swing.JLabel();
        gameTimeLabel = new javax.swing.JLabel();
        gameTimeTitleLabel = new javax.swing.JLabel();
        currentRoomLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        borselloTextArea = new javax.swing.JTextArea();
        borselloTitleLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        helpMenuCommandsList = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(804, 560));

        gameTextArea.setEditable(false);
        gameTextArea.setBackground(new java.awt.Color(0, 0, 0));
        gameTextArea.setColumns(20);
        gameTextArea.setForeground(new java.awt.Color(255, 255, 255));
        gameTextArea.setRows(5);
        jScrollPane1.setViewportView(gameTextArea);

        gameTextField.setBackground(new java.awt.Color(0, 0, 0));
        gameTextField.setForeground(new java.awt.Color(255, 255, 255));

        sendButton.setBackground(new java.awt.Color(0, 0, 0));
        sendButton.setForeground(new java.awt.Color(102, 102, 102));
        sendButton.setLabel("Invia");

        currentRoomTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        currentRoomTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentRoomTitleLabel.setText("Stanza Corrente");

        gameTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        gameTimeLabel.setText("*DEFAULT*");

        gameTimeTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        gameTimeTitleLabel.setText("Tempo di Gioco");

        currentRoomLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentRoomLabel.setText("*DEFAULT*");

        borselloTextArea.setEditable(false);
        borselloTextArea.setBackground(new java.awt.Color(0, 0, 0));
        borselloTextArea.setColumns(16);
        borselloTextArea.setForeground(new java.awt.Color(102, 102, 102));
        borselloTextArea.setRows(5);
        jScrollPane2.setViewportView(borselloTextArea);

        borselloTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        borselloTitleLabel.setText("Borsello:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(sendButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(borselloTitleLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(gameTimeTitleLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(currentRoomLabel)
                                        .addGap(17, 17, 17)))))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(currentRoomTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(gameTimeLabel)
                                .addGap(93, 93, 93))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(gameTimeTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gameTimeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(currentRoomTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(borselloTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        helpMenu.setText("Help");

        helpMenuCommandsList.setText("Lista comandi");
        helpMenuCommandsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuCommandsListActionPerformed(evt);
            }
        });
        helpMenu.add(helpMenuCommandsList);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpMenuCommandsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuCommandsListActionPerformed
        JOptionPane.showMessageDialog(this,

            "\t\t--- Come giocare ad Hive Mind ---\n"
            + "\n"
            + "E' possibile usare questi comandi testuali anche senza premere i relativi pulsanti:\n"
            + "\n"
            + ">> nord - Spostati in direzione nord\n"
            + ">> est - Spostati in direzione est\n"
            + ">> ovest - Spostati in direzione ovest\n"
            + ">> sud - Spostati in direzione sud\n"
            + ">> osserva - permette di guardarti intorno ed esaminare l'ambiente circostante\n"
            + ">> carica - carica un salvataggio\n"
            + ">> salva - salva la partita corrente\n"
            + ">> help - stampa una lista dei comandi\n"
            + "\n"
            + "Altri comandi:\n"
            + "\n"
            + ">> esamina [qualcosa] - esamina qualcosa presente nella stanza, o prendi oggetti da un cadavere\n"
            + ">> inventario - visualizza l'inventario\n"
            + ">> equipaggia [oggetto] - equipaggia un oggetto dell'inventario (massimo 2 alla volta)\n"
            + ">> togli [oggetto] - disequipaggia un oggetto\n"
            + ">> apri [oggetto contenitore] - apri un oggetto specifico\n"
            + ">> chiudi [oggetto contenitore] - chiudi un oggetto specifico\n"
            + ">> lascia [oggetto] - lascia un oggetto in una stanza\n"
            + ">> metti [oggetto] in [oggetto contenitore] - metti un oggetto in un contenitore valido\n"
            + ">> prendi [oggetto] - prendi un oggetto a terra nella stanza o in un contenitore\n"
            + ">> parla a [personaggio] - parla ad un personaggio nella stanza\n"
            + ">> dai [oggetto] a [persona] - dai un oggetto nel tuo inventario ad un personaggio\n"
            + ">> usa [oggetto] -  usa oggetti esterni al tuo inventario\n"
            + "Altri comandi più specifici dovranno essere trovati dal giocatore.\n"
            + "\n"
            + "Per salvare o caricare una partita, sovrascrivere il file HiveMindGame.dat situato in\n"
            + "../hivemind/hivemind/HiveMindGame.dat", "Lista comandi", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_helpMenuCommandsListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea borselloTextArea;
    private javax.swing.JLabel borselloTitleLabel;
    private javax.swing.JLabel currentRoomLabel;
    private javax.swing.JLabel currentRoomTitleLabel;
    private javax.swing.JTextArea gameTextArea;
    private javax.swing.JTextField gameTextField;
    private javax.swing.JLabel gameTimeLabel;
    private javax.swing.JLabel gameTimeTitleLabel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuCommandsList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
