/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameInterface;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

//import da engine
import games.PasquettaDaComa;
import parser.Parser;
import parser.ParserOutput;
import type.CommandType;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import java.util.Set;
import adventure.*;

/**
 *
 * @author Clah865
 */
public class UserInterface extends javax.swing.JFrame {
    
    private final GameDescription game;
    
    private Parser parser;

        public Engine(GameDescription game) {
            
        }

        public void execute() {
            gameTextArea.setText("================================");
            gameTextArea.append("\n* Adventure v. 0.2 - 2020-2021 *");
            gameTextArea.append("\n================================\n");
            currentRoomLabel.setText(game.getCurrentRoom().getName());
            gameTextArea.append("");
            gameTextArea.append(game.getCurrentRoom().getDescription());
            gameTextArea.append("");
            
        }

    

    public class Timer extends Thread {

        @Override
        public void run() {

            int secondi = 0;
            int minuti = 0;
            while (true) {
                if (secondi < 59) {
                    secondi++;
                } else {
                    secondi = 0;
                    minuti++;
                }

                String tDisplay = String.format("%02d:%02d", minuti, secondi);
                try {
                    Timer.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
                gameTimeLabel.setText(tDisplay);

            }
        }
    }

    /**
     * Creates new form userInterface
     */
    public UserInterface() {
        
        this.game = game;
            try {
                this.game.init();
            } catch (Exception ex) {
                System.err.println(ex);
            }
            try {
                Set<String> stopwords = Utils.loadFileListInSet(new File("./resources/stopwords"));
                parser = new Parser(stopwords);
            } catch (IOException ex) {
                System.err.println(ex);
            }

        initComponents();
        init();
        
    }

    private void init() {
         
        (new Timer()).start();

        Engine engine = new Engine(new PasquettaDaComa());
        engine.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameTextArea = new javax.swing.JTextArea();
        gameTextField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        currentRoomTitleLabel = new javax.swing.JLabel();
        gameTimeLabel = new javax.swing.JLabel();
        gameTimeTitleLabel = new javax.swing.JLabel();
        currentRoomLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        borselloTextArea = new javax.swing.JTextArea();
        borselloTitleLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        helpMenuCommandsList = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(804, 560));

        gameTextArea.setEditable(false);
        gameTextArea.setBackground(new java.awt.Color(0, 0, 0));
        gameTextArea.setColumns(20);
        gameTextArea.setForeground(new java.awt.Color(255, 255, 255));
        gameTextArea.setRows(5);
        jScrollPane1.setViewportView(gameTextArea);

        gameTextField.setBackground(new java.awt.Color(0, 0, 0));
        gameTextField.setForeground(new java.awt.Color(255, 255, 255));

        sendButton.setBackground(new java.awt.Color(0, 0, 0));
        sendButton.setForeground(new java.awt.Color(102, 102, 102));
        sendButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        sendButton.setLabel("Invia");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        currentRoomTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        currentRoomTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentRoomTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentRoomTitleLabel.setText("Stanza Corrente");

        gameTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        gameTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameTimeLabel.setText("*DEFAULT*");

        gameTimeTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        gameTimeTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameTimeTitleLabel.setText("Tempo di Gioco");

        currentRoomLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentRoomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentRoomLabel.setText("*DEFAULT*");

        borselloTextArea.setEditable(false);
        borselloTextArea.setBackground(new java.awt.Color(0, 0, 0));
        borselloTextArea.setColumns(16);
        borselloTextArea.setForeground(new java.awt.Color(102, 102, 102));
        borselloTextArea.setRows(5);
        jScrollPane2.setViewportView(borselloTextArea);

        borselloTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        borselloTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borselloTitleLabel.setText("Borsello:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gameTextField)
                        .addGap(18, 18, 18)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentRoomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentRoomTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(gameTimeTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gameTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borselloTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(gameTimeTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gameTimeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(currentRoomTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(borselloTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        helpMenu.setText("Help");

        helpMenuCommandsList.setText("Lista comandi");
        helpMenuCommandsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuCommandsListActionPerformed(evt);
            }
        });
        helpMenu.add(helpMenuCommandsList);

        aboutMenu.setText("About");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenu);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpMenuCommandsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuCommandsListActionPerformed
        JOptionPane.showMessageDialog(this,
                "\t\t--- Come giocare ad Pasquetta da Coma ---\n"
                + "\n"
                + "Utilizza questi comandi per spostarti nelle varie stanze:\n"
                + "\n"
                + ">> nord - Spostati in direzione nord\n"
                + ">> est - Spostati in direzione est\n"
                + ">> ovest - Spostati in direzione ovest\n"
                + ">> sud - Spostati in direzione sud\n"
                + "\n"
                + "Altri comandi:\n"
                + ">> osserva - permette di guardarti intorno ed esaminare l'ambiente circostante\n"
                + ">> help - stampa una lista dei comandi\n"
                + ">> esamina [qualcosa] - esamina qualcosa presente nella stanza\n"
                + ">> apri [oggetto contenitore] - apri un oggetto specifico\n"
                + ">> chiudi [oggetto contenitore] - chiudi un oggetto specifico\n"
                + ">> lascia [oggetto] - lascia un oggetto in una stanza\n"
                + ">> metti [oggetto] in [oggetto contenitore] - metti un oggetto in un contenitore valido\n"
                + ">> prendi [oggetto] - prendi un oggetto a terra nella stanza o in un contenitore\n"
                + ">> parla a [personaggio] - parla ad un personaggio nella stanza\n"
                + ">> dai [oggetto] a [persona] - dai un oggetto nel tuo inventario ad un personaggio\n"
                + ">> usa [oggetto] -  usa oggetti presenti nel tuo inventario\n"
                + "Altri comandi più specifici dovranno essere trovati dal giocatore.\n"
                + "\n");
    }//GEN-LAST:event_helpMenuCommandsListActionPerformed

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        JOptionPane.showMessageDialog(this, "Pasquetta da Coma è un gioco d'avventura testuale, \nnel quale puoi inserire dei comandi da tastiera "
                + "per esplorare la mappa \ne risolvere i vari enigmi presenti all'interno del gioco. \nRicordati di raccogliere gli oggetti "
                + "per proseguire con l'avventura.\n\nSfruttare le descrizioni degli oggetti sarà fondamentale \nper proseguire la storia e"
                + "ricoradti sempre\n\n Fai sempre la scelta giusta!!", "Pasquetta da Coma", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed

        //Scanner scanner = new Scanner(System.in);
            //while (scanner.hasNextLine()) {
                String command = gameTextField.getText();
                ParserOutput p = parser.parse(command, game.getCommands(), game.getCurrentRoom().getObjects(), game.getInventory());
                if (p.getCommand() != null && p.getCommand().getType() == CommandType.END) {
                    System.out.println("Addio!");
                    //break;
                } else {
                    game.nextMove(p, System.out);
                    System.out.println();
                }
            //}
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JTextArea borselloTextArea;
    private javax.swing.JLabel borselloTitleLabel;
    private javax.swing.JLabel currentRoomLabel;
    private javax.swing.JLabel currentRoomTitleLabel;
    private javax.swing.JTextArea gameTextArea;
    private javax.swing.JTextField gameTextField;
    private javax.swing.JLabel gameTimeLabel;
    private javax.swing.JLabel gameTimeTitleLabel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuCommandsList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
